# Generated by Django 2.1 on 2018-10-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_fileupload_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to='data/unprocessed/'),
        ),
    ]
