# Generated by Django 2.1 on 2018-09-17 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180829_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(max_length=100, unique=True)),
                ('location', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='aid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Affiliation'),
        ),
    ]
