# Generated by Django 2.1 on 2018-10-01 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemsdb', '0001_initial'),
        ('users', '0006_auto_20180917_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_chroma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chroma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemsdb.chromatography')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Column_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemsdb.analytical_column')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_hrms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HRMS_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemsdb.hrms_system')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
